BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "headlines" (
	"id"	INTEGER,
	"headline"	TEXT,
	"firstSeen"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"lastSeen"	TEXT DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);
COMMIT;
